[server]
enableCORS = false
enableXsrfProtection = false
headless = true
maxUploadSize = 50
enableWebsocketCompression = true
runOnSave = true
port = 8501
address = "0.0.0.0"
enableStaticServing = true
baseUrlPath = ""
fileWatcherType = "none"
maxMessageSize = 200
enableCookieBasedSessionHandling = true
cookieSecret = "${STREAMLIT_SERVER_COOKIE_SECRET}"
cookieExpiryDays = 30
enableXFrameOptions = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[runner]
magicEnabled = true
fastReruns = true
enforceSerializableSessionState = false
postScriptGC = true

[client]
showErrorDetails = true
toolbarMode = "minimal"
caching = true
displayEnabled = true

[global]
developmentMode = false
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false
disableWatchdogWarning = true
showWidgetCallbackWarning = false

[mapbox]
token = ""